### PR TITLE
Rework charset to support combining charsets

### PR DESCRIPTION
**Pull request by Lucky2307**
## What's changed
Charset params is reworked as per #65, allowing the combination of charsets allowing more flexibility.
```
  l | abcdefghijklmnopqrstuvwxyz [a-z]
  u | ABCDEFGHIJKLMNOPQRSTUVWXYZ [A-Z]
  d | 0123456789                 [0-9]
  h | 0123456789abcdef           [0-9a-f]
  H | 0123456789ABCDEF           [0-9A-F]
  s |  !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
```
## Caveats
1. There is currently no duplicate check, so if the user inputs `-c uu`, there will be two sets of uppercase letters in the final charset.
2. The symbols charset collection has grown significantly, making the runtime considerably longer when used.
3. When printed out to the terminal, due to the nature of debug representation, the final charsets will include escape backslash (i.e., `... '\'', '\\', ...`) (can be fixed by joining them as string and printing them out normally).

(Do tell me if any of these should be fixed before merging)

## Future works
- Maybe allow the user to further customize charset, like letting the user specify their own charset. Something like `-c r/!?@.\/*^/`, so that the user can only select common symbols to generate with.
  - Allow the user to make "patterns". For example, generates random words with patterns lowercase -> digits (e.g., word09, hello1998, ab12345)

### <sub>Small note</sub>
<sup>This is my first ever real work on Rust coming from other language, so any guidance regarding common sense, best practices, concepts, etc. is appreciated.</sup>

### CODE REVIEW

**Comment by agourlay** [comment]
@Lucky2307 Thank you very much for you contribution!

This PR looks very promising.

Regarding the caveats you highlighting:

1. the duplicate check in the final charset is necessary
2. maybe we need to split those symbols, have you checked what Hashcat is doing there?
3. pretty printing would be a nice touch

**Comment by Lucky2307** [comment]
I took a look at hashcat's docs about the charsets itself, it seems they are fundamentally different. They use masks which gives more control over the characters range, but also requires the exact length of the password itself.
E.g., If I knew that the password starts with "pass" and ends with 2 digits I can use `pass?d?d` as the mask. If I only know that the password starts with 4 lowercase letters and ends with 2 digits I can use `?l?l?l?l?d?d` as the mask.

While they do have the increment option, it's not perfect. In my previous example, if I don't know the length of the lowercase letters, I will be out of luck. From what I understand, the way the increment option works is that it will start with 0 or 1 requested charset, and keep incrementing (adding more of the requested charsets) if the password is not found. So the previous example with increment option would look like:
```
?l
?l?l
?l?l?l
?l?l?l?l
?l?l?l?l?d
?l?l?l?l?d?d
```
While the preferred increment is something like:
```
?l?d?d
?l?l?d?d
?l?l?l?d?d
?l?l?l?l?d?d
```

Changing the method to these kind of mask attack not only need rework on the charsets, but also on the password generation method as a whole.
I might try to implement mask attack when I have the time (am quite busy for the next weeks or so). The question will be is it going to replace the brute force method as a whole or add is as an option?

**Comment by agourlay** [comment]
Thanks for the analysis :+1: 

Let's keep mask attack out of this PR, this represents a lot of work.
In the future it might make sense to offer both brute force & mask attack strategies, I have not thought about it that much.

Then only caveats 1 & 3 makes sense at the moment

**Comment by agourlay** [comment]
@Lucky2307 gentle ping to know if you need help for me :)

Are you still interested in wrapping up this PR or should I take over?

I don't mean to rush you, finishing this PR is not a high priority.

**Comment by Lucky2307** [comment]
> @Lucky2307 gentle ping to know if you need help for me :)
> 
> Are you still interested in wrapping up this PR or should I take over?
> 
> I don't mean to rush you, finishing this PR is not a high priority.

Yep sorry, I'm still interested in finishing it. My laptop broke down so I couldn't finish it on the go.

I should be able to update this PR around tomorrow night.

**Comment by agourlay** [comment]
No worries take your time, sorry to hear about your hardware issues.

**Comment by Lucky2307** [comment]
@agourlay sorry for the long wait, finally able to update the branch.
- The charset input now enforces element distinctness using hashset.
- The charset info in terminal now prints as-is. i.e.:
  - ```
    Generating passwords with length from 1 to 10 for charset with length 36
    abcdefghijklmnopqrstuvwxyz0123456789
    ```

**Pull request merged**
